// Mock Profiles representing specific behavioral archetypes and statistical anomalies
export const MOCK_PROFILES = {
  "whiffgod#na1": {
    name: "WhiffGod",
    tag: "NA1",
    region: "na",
    rank: "Silver 1",
    rankTier: 10,
    avatar: "/avatars/phoenix.jpg", // Phoenix High-Res Portrait
    frequentTeammates: [
      { name: "EcoThrower", tag: "NA1", region: "na", gamesTogether: 18, topAgent: "Chamber", avatar: "/avatars/jett.jpg", synergy: "Eco Degenerates" },
      { name: "OneTrickReyna", tag: "NA1", region: "na", gamesTogether: 14, topAgent: "Reyna", avatar: "/avatars/reyna.jpg", synergy: "Double Whiff Duo" },
      { name: "BalancedPro", tag: "NA1", region: "na", gamesTogether: 7, topAgent: "Omen", avatar: "/avatars/omen.jpg", synergy: "Long-Suffering Controller" }
    ],
    stats: {
      kd: 0.74,
      acs: 142,
      kast: 52,
      adr: 98,
      headshotPct: 11,
      bodyPct: 51,
      legshotPct: 38,
      firstBloodPct: 8,
      firstDeathPct: 34,
      clutchPct: 4,
      clutchAttempts: 25,
      clutchWins: 1,
      killsPerRound: 0.52,
      deathsPerRound: 0.89,
      winRate: 38,
      totalGames: 140,
      topAgent: "Phoenix",
      topAgentShare: 45,
      topAgentKd: 0.71,
      top3Agents: [
        { name: "Phoenix", share: 45, kd: 0.71, winRate: 36 },
        { name: "Reyna", share: 30, kd: 0.78, winRate: 40 },
        { name: "Jett", share: 25, kd: 0.72, winRate: 38 }
      ],
      uniqueAgentsCount: 3,
      roleDistribution: { Duelist: 100, Initiator: 0, Controller: 0, Sentinel: 0 },
      highestWinRateMap: { name: "Ascent", winRate: 48, games: 35 },
      lowestWinRateMap: { name: "Lotus", winRate: 19, games: 42 },
      ecoEfficiency: 28,
      operatorBuyFreq: 15,
      postOpWinRate: 20
    }
  },
  "onetrickreyna#na1": {
    name: "OneTrickReyna",
    tag: "NA1",
    region: "na",
    rank: "Gold 2",
    rankTier: 14,
    avatar: "/avatars/reyna.jpg", // Reyna High-Res Portrait
    stats: {
      kd: 0.82,
      acs: 175,
      kast: 58,
      adr: 118,
      headshotPct: 19,
      bodyPct: 62,
      legshotPct: 19,
      firstBloodPct: 14,
      firstDeathPct: 26,
      clutchPct: 12,
      clutchAttempts: 33,
      clutchWins: 4,
      killsPerRound: 0.61,
      deathsPerRound: 0.82,
      winRate: 41,
      totalGames: 210,
      topAgent: "Reyna",
      topAgentShare: 89,
      topAgentKd: 0.81,
      top3Agents: [
        { name: "Reyna", share: 89, kd: 0.81, winRate: 40 },
        { name: "Jett", share: 8, kd: 0.92, winRate: 50 },
        { name: "Sage", share: 3, kd: 0.75, winRate: 33 }
      ],
      uniqueAgentsCount: 3,
      roleDistribution: { Duelist: 97, Controller: 0, Initiator: 0, Sentinel: 3 },
      highestWinRateMap: { name: "Haven", winRate: 49, games: 50 },
      lowestWinRateMap: { name: "Breeze", winRate: 28, games: 46 },
      ecoEfficiency: 45,
      operatorBuyFreq: 8,
      postOpWinRate: 35
    }
  },
  "miragemaster#eu1": {
    name: "MirageMaster",
    tag: "EU1",
    region: "eu",
    rank: "Platinum 3",
    rankTier: 18,
    avatar: "/avatars/jett.jpg", // Yoru / Jett High-Res
    stats: {
      kd: 1.38,
      acs: 272,
      kast: 54,
      adr: 178,
      headshotPct: 29,
      bodyPct: 56,
      legshotPct: 15,
      firstBloodPct: 22,
      firstDeathPct: 31,
      clutchPct: 6,
      clutchAttempts: 32,
      clutchWins: 2,
      killsPerRound: 0.94,
      deathsPerRound: 0.68,
      winRate: 37,
      totalGames: 165,
      topAgent: "Yoru",
      topAgentShare: 62,
      topAgentKd: 1.42,
      top3Agents: [
        { name: "Yoru", share: 62, kd: 1.42, winRate: 36 },
        { name: "Jett", share: 22, kd: 1.30, winRate: 40 },
        { name: "Reyna", share: 16, kd: 1.35, winRate: 38 }
      ],
      uniqueAgentsCount: 4,
      roleDistribution: { Duelist: 100, Controller: 0, Initiator: 0, Sentinel: 0 },
      highestWinRateMap: { name: "Bind", winRate: 46, games: 40 },
      lowestWinRateMap: { name: "Icebox", winRate: 22, games: 38 },
      ecoEfficiency: 35,
      operatorBuyFreq: 22,
      postOpWinRate: 30
    }
  },
  "legshotking#kr1": {
    name: "LegshotKing",
    tag: "KR1",
    region: "kr",
    rank: "Bronze 3",
    rankTier: 9,
    avatar: "/avatars/phoenix.jpg", // Killjoy / Phoenix High-Res
    stats: {
      kd: 0.81,
      acs: 151,
      kast: 60,
      adr: 104,
      headshotPct: 8,
      bodyPct: 44,
      legshotPct: 48,
      firstBloodPct: 6,
      firstDeathPct: 20,
      clutchPct: 9,
      clutchAttempts: 22,
      clutchWins: 2,
      killsPerRound: 0.55,
      deathsPerRound: 0.78,
      winRate: 44,
      totalGames: 95,
      topAgent: "Killjoy",
      topAgentShare: 54,
      topAgentKd: 0.83,
      top3Agents: [
        { name: "Killjoy", share: 54, kd: 0.83, winRate: 46 },
        { name: "Cypher", share: 28, kd: 0.78, winRate: 42 },
        { name: "Brimstone", share: 18, kd: 0.80, winRate: 40 }
      ],
      uniqueAgentsCount: 3,
      roleDistribution: { Sentinel: 82, Controller: 18, Duelist: 0, Initiator: 0 },
      highestWinRateMap: { name: "Split", winRate: 52, games: 25 },
      lowestWinRateMap: { name: "Sunset", winRate: 31, games: 29 },
      ecoEfficiency: 52,
      operatorBuyFreq: 2,
      postOpWinRate: 10
    }
  },
  "ecothrower#na1": {
    name: "EcoThrower",
    tag: "NA1",
    region: "na",
    rank: "Silver 3",
    rankTier: 12,
    avatar: "/avatars/jett.jpg", // Chamber / Jett High-Res
    stats: {
      kd: 0.88,
      acs: 168,
      kast: 56,
      adr: 115,
      headshotPct: 22,
      bodyPct: 58,
      legshotPct: 20,
      firstBloodPct: 15,
      firstDeathPct: 29,
      clutchPct: 8,
      clutchAttempts: 18,
      clutchWins: 1,
      killsPerRound: 0.60,
      deathsPerRound: 0.82,
      winRate: 42,
      totalGames: 110,
      topAgent: "Chamber",
      topAgentShare: 65,
      topAgentKd: 0.86,
      top3Agents: [
        { name: "Chamber", share: 65, kd: 0.86, winRate: 41 },
        { name: "Jett", share: 20, kd: 0.94, winRate: 45 },
        { name: "Reyna", share: 15, kd: 0.88, winRate: 40 }
      ],
      uniqueAgentsCount: 3,
      roleDistribution: { Sentinel: 65, Duelist: 35, Controller: 0, Initiator: 0 },
      highestWinRateMap: { name: "Breeze", winRate: 48, games: 30 },
      lowestWinRateMap: { name: "Ascent", winRate: 24, games: 35 },
      ecoEfficiency: 18,
      operatorBuyFreq: 38,
      postOpWinRate: 15
    }
  },
  "mapcursed#ap1": {
    name: "MapCursed",
    tag: "AP1",
    region: "ap",
    rank: "Gold 3",
    rankTier: 15,
    avatar: "/avatars/omen.jpg", // Sova / Omen High-Res
    stats: {
      kd: 1.05,
      acs: 205,
      kast: 68,
      adr: 138,
      headshotPct: 24,
      bodyPct: 62,
      legshotPct: 14,
      firstBloodPct: 12,
      firstDeathPct: 14,
      clutchPct: 18,
      clutchAttempts: 28,
      clutchWins: 5,
      killsPerRound: 0.72,
      deathsPerRound: 0.69,
      winRate: 54,
      totalGames: 180,
      topAgent: "Sova",
      topAgentShare: 58,
      topAgentKd: 1.10,
      top3Agents: [
        { name: "Sova", share: 58, kd: 1.10, winRate: 56 },
        { name: "Fade", share: 25, kd: 1.02, winRate: 52 },
        { name: "Gekko", share: 17, kd: 0.98, winRate: 50 }
      ],
      uniqueAgentsCount: 4,
      roleDistribution: { Initiator: 100, Duelist: 0, Controller: 0, Sentinel: 0 },
      highestWinRateMap: { name: "Ascent", winRate: 72, games: 45 },
      lowestWinRateMap: { name: "Lotus", winRate: 16, games: 44 },
      ecoEfficiency: 62,
      operatorBuyFreq: 5,
      postOpWinRate: 40
    }
  },
  "judgeonly#ap1": {
    name: "JudgeOnly",
    tag: "AP1",
    region: "ap",
    rank: "Diamond 1",
    rankTier: 19,
    avatar: "/avatars/phoenix.jpg", // Breach / Phoenix High-Res
    stats: {
      kd: 0.98,
      acs: 190,
      kast: 62,
      adr: 135,
      headshotPct: 6,
      bodyPct: 68,
      legshotPct: 26,
      firstBloodPct: 18,
      firstDeathPct: 28,
      clutchPct: 10,
      clutchAttempts: 30,
      clutchWins: 3,
      killsPerRound: 0.68,
      deathsPerRound: 0.70,
      winRate: 49,
      totalGames: 220,
      topAgent: "Raze",
      topAgentShare: 72,
      topAgentKd: 1.01,
      top3Agents: [
        { name: "Raze", share: 72, kd: 1.01, winRate: 50 },
        { name: "Breach", share: 18, kd: 0.92, winRate: 47 },
        { name: "Neon", share: 10, kd: 0.88, winRate: 45 }
      ],
      uniqueAgentsCount: 3,
      roleDistribution: { Duelist: 82, Initiator: 18, Controller: 0, Sentinel: 0 },
      highestWinRateMap: { name: "Split", winRate: 64, games: 60 },
      lowestWinRateMap: { name: "Breeze", winRate: 26, games: 50 },
      ecoEfficiency: 38,
      operatorBuyFreq: 4,
      postOpWinRate: 25
    }
  },
  "balancedpro#na1": {
    name: "BalancedPro",
    tag: "NA1",
    region: "na",
    rank: "Ascendant 2",
    rankTier: 23,
    avatar: "/avatars/omen.jpg", // Omen High-Res
    stats: {
      kd: 1.15,
      acs: 228,
      kast: 76,
      adr: 148,
      headshotPct: 26,
      bodyPct: 61,
      legshotPct: 13,
      firstBloodPct: 16,
      firstDeathPct: 12,
      clutchPct: 22,
      clutchAttempts: 36,
      clutchWins: 8,
      killsPerRound: 0.78,
      deathsPerRound: 0.68,
      winRate: 56,
      totalGames: 310,
      topAgent: "Omen",
      topAgentShare: 42,
      topAgentKd: 1.18,
      top3Agents: [
        { name: "Omen", share: 42, kd: 1.18, winRate: 58 },
        { name: "Viper", share: 32, kd: 1.12, winRate: 55 },
        { name: "Clove", share: 26, kd: 1.14, winRate: 54 }
      ],
      uniqueAgentsCount: 5,
      roleDistribution: { Controller: 100, Duelist: 0, Initiator: 0, Sentinel: 0 },
      highestWinRateMap: { name: "Lotus", winRate: 62, games: 70 },
      lowestWinRateMap: { name: "Icebox", winRate: 49, games: 65 },
      ecoEfficiency: 74,
      operatorBuyFreq: 6,
      postOpWinRate: 50
    }
  }
};
